<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <AssemblyName>HollowLoader</AssemblyName>
    <RootNamespace>HollowLoader</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
    <Deterministic>true</Deterministic>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <!-- Retarget to net48 if you need to run on hosts without .NET 8 runtime -->
  </PropertyGroup>

</Project>
